name: colorfulcurves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-image
  - numpy
  - scipy
  - py-opencv
  - pillow
  - cython
  - pip
  - git
  - pip:
     - git+https://github.com/yig/python-qtwidgets
     - git+https://github.com/yig/pyqt-colorpicker
     - qtpy
     - pyside6
     - pyqtgraph
     - pyopencl
